apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-3he6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xxij-tenant/rhtap-demo-app/hacbs-test-project-3he6@sha256:782bc2e942dceedf4cc5bd732ca0d7e025d5ab30c1bfb6b0be81e0a7eb835a76
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
