apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-3he6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xxij-tenant/rhtap-demo-app/hacbs-test-project-3he6@sha256:eb96e559231cc4b630cc2133e8014f51e525fb4d793fd82f1638f354fa41099d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
