apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-3he6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-3he6
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-3he6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-3he6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-3he6
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xxij-tenant/rhtap-demo-app/hacbs-test-project-3he6@sha256:782bc2e942dceedf4cc5bd732ca0d7e025d5ab30c1bfb6b0be81e0a7eb835a76
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
